---
title: "R Notebook- MYb11-mediated protection: soft agar Bt inhibition & growth Kirbies"
output: html_notebook
---

```{r Load packages & set directory}

library(ggplot2); library(dplyr); library(multcomp); library(readxl); library(RColorBrewer)

# Set working directory to source location
currentDirectory <- dirname(rstudioapi::getActiveDocumentContext()$path)
```


```{r SOFT AGAR Open data, organize and plot}

data <- read.csv("MYb11-mediated-protection_Fig3_data_soft-agar-inhibition.csv", header = T)

# Exclude faulty plates
data <- data[complete.cases(data$consider), ]
data <- subset(data, select=-c(consider, raw_measurement, average_9cm_plate_in_run_images))

# Grab ampicillin inhibition zones & attach as type inhibition in data frame
ampicillin <- data[data$type == "ampicillin",'mm']
data <- data[data$type != "ampicillin",]
nplates <- length(data$strain)/2
data <- rbind(data, data.frame(strain = rep("ampicillin", nplates*2),
                               ID = rep("ampicillin", nplates*2),
                               run = data$run,
                               replicate = rep(seq(1:(nplates)),2), 
                               type = c(rep("inhibition", nplates),rep("colony", nplates)),
                               mm = c(ampicillin, rep(0, length(ampicillin)))))

# Calculate the difference between inhibition and colony diameter
# colonies <- data[data$type == "colony", ]
# inhibitions <- data[data$type == "inhibition", ]
# data <- merge(colonies, inhibitions, by = c("strain", "replicate"))
# colnames(data)[colnames(data)%in%c("mm.x", "mm.y")] <- c("colony_mm", "inhibition_mm")
# data <- subset(data, select=-c(type.x, type.y))
# data$inhibition_zone <- data$inhibition_mm - data$colony_mm/data$colony_mm

### === Plotting === #######

strainOrder <- c("MYb11", "MT2", "MT3", "MT5", "MT11", "MT12", "MT13", "MT14","MYb12", "MYb115", "OP50", "ampicillin")
data$strain <- factor(data$strain, levels = strainOrder)

main <- data[!data$strain%in%c("MT14", "MYb12", "MYb115"),]

colorscheme <- c("darkred", rep("grey", 3), "lightblue", rep("grey",5), rep("black", 3))
colorscheme <- c("black", brewer.pal(n=9, name= "Spectral")[1:3], rev(brewer.pal(n=9, name="Spectral")[7:9]),"darkgrey","grey")
                 
g <- ggplot(main[main$type == "inhibition", ], aes(x=strain, y=mm, col = strain))+
    geom_point(aes(y= max(main[, 'mm'])*1.1), alpha = 0)+ # leave space for p-value on top
  geom_boxplot(outlier.shape = NA)+
  stat_boxplot(geom='errorbar', linetype=1, width=0.3)+  #whiskers
  geom_jitter(size = 1, width = 0.1, height = 0)+
  labs(x="Bacterial isolate", y= "Inhibition zone (mm)")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust =1))+
  scale_color_manual(values=colorscheme)+
  scale_fill_manual(values=colorscheme)+
  theme(legend.position = "none",
        legend.text = element_text(size = 10), 
        legend.title = element_text(size = 0), 
        legend.background = element_rect(fill = "transparent"), 
        axis.text.x = element_text(size = 10), 
        strip.text.x = element_text(size = 10), 
        strip.text.y = element_text(size = 10), 
        axis.text.y = element_text(hjust = 1, size = 10))

ggsave(paste(inhibitionDirectory, "soft-agar-inhibition_morphotypes_bt247_inhibition-total_main.svg", sep=""), width = 4, height =3)

```

```{r SOFT AGAR Compare bacterial isolates to MYb11 ancestor as reference}
# Based on visual inspection of the data, normality and homogeneity of variances were assumed for further analysis
m <- lm(mm ~ strain + run, data = main[main$type == "inhibition", ])
anova(m)

# Run does not have a significant impact, thus plot all together
summary(glht(m, linfct = mcp(strain = "Dunnett")))

# Comparing MT3 and MT11 directly, is there a difference?
t.test(main[main$type == "inhibition" & main$strain == "MT3", "mm"], 
       main[main$type == "inhibition" & main$strain == "MT11", "mm"])
# No, there is not.

```


```{r GROWTH INHIBITION Open data and organize}

growth <- read_xlsx("MYb11-mediated-protection_Fig3_data_growth-in-competition_24h.xlsx", sheet = 1)

# Focus on Bt247
growth <- growth[growth$treat == "Bt247",]
growth[growth$bac == "amp", 'bac'] <- "ampicillin"
growth[growth$bac == "Myb11", 'bac'] <- "MYb11"

strainOrder <- c("MYb11", "MT2", "MT3", "MT5", "MT11", "MT12", "MT13", "MT14","OP50", "ampicillin")
growth$bac <- factor(growth$bac, levels = strainOrder)

main <- growth[!growth$bac%in%c("MT14", "ampicillin"),]

colorscheme <- c("darkred", rep("grey", 3), "lightblue", rep("grey",5), rep("black", 3))
colorscheme <- c("black", brewer.pal(n=9, name= "Spectral")[1:3], rev(brewer.pal(n=9, name="Spectral")[7:9]),"darkgrey","grey")

# Plot representative plot (run 4) of overall statistics
g <- ggplot(main[main$run == 4,], aes(x=bac, y=dia, col = bac, fill =  bac))+# remove fill for colonies w/o inhibition zone manually
  geom_point(aes(y= max(main[main$run == 4, 'dia'])*1.1), alpha = 0)+ # leave space for p-value on top
  geom_jitter(size = 5, width = 0.1, height = 0)+
  labs(x="Bacterial isolate", y= "Growth diameter (mm)")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust =1))+
  scale_color_manual(values=colorscheme)+
  scale_fill_manual(values=colorscheme)+
  theme(legend.position = "none",
        legend.text = element_text(size = 10), 
        legend.title = element_text(size = 0), 
        legend.background = element_rect(fill = "transparent"), 
        axis.text.x = element_text(size = 10), 
        strip.text.x = element_text(size = 10), 
        strip.text.y = element_text(size = 10), 
        axis.text.y = element_text(hjust = 1, size = 10)) 
g

ggsave(paste(inhibitionDirectory, "growth-in-competition_morphotypes_bt247_inhibition-total_main.svg", sep=""), width = 4, height =3)

# keep fill for those with inhibition zone in at least one run: MYb11, MT2, MT12, MT13

```

```{r GROWTH INHIBITION Compare bacterial isolates to MYb11 ancestor as reference}
# Based on visual inspection of the data, normality and homogeneity of variances were assumed for further analysis
m <- lm(dia ~ bac + run, data = main)
anova(m)

# Run does have a significant impact, thus plot representative run

m <- lm(dia ~ bac, data = main[main$run == 4, ])
anova(m)

summary(glht(m, linfct = mcp(bac = "Dunnett")))

```